name: GPFramework
main: io.github.grassproject.framework.GPFrameworkPlugin
bootstrapper: io.github.grassproject.framework.GPFrameworkBootstrap
loader: io.github.grassproject.framework.GPFrameworkLoader
version: '${version}'
api-version: '1.21'
author: GrassProject
description: PluginFramework
load: STARTUP
dependencies:
  server:
    Vault:
      required: false
      join-classpath: true
    LuckPerms:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true