name: GPFramework
version: '${version}'
author: GrassProject

api-version: "1.21"
description: PluginFramework
load: STARTUP

main: io.github.grassproject.framework.GPFrameworkPlugin
bootstrapper: io.github.grassproject.framework.GPFrameworkBootstrap
loader: io.github.grassproject.framework.GPFrameworkLoader

dependencies:
  server:
    Vault:
      required: false
      join-classpath: true
    LuckPerms:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true