name: GPLibrary
main: io.github.grassproject.gplibrary.GPLibraryPlugin
version: '${version}'
api-version: '1.21'
author: GrassProject
description: PluginLibrary
# load: STARTUP
libraries:
# - com.zaxxer:HikariCP:6.0.0