name: GPLibrary
main: io.github.grassproject.gplibrary.GPLibraryPlugin
version: '${version}'
api-version: '1.21'
author: GrassProject
description: PluginLibrary
load: STARTUP
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.21