name: GPFramework
main: io.github.grassproject.framework.GPFrameworkPlugin
version: '${version}'
api-version: '1.21'
author: GrassProject
description: PluginFramework
load: STARTUP
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0